version: 1.0
configuration:
  custom:    
  core:
    name: $APPLICATION_NAME$
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    logoColor: DarkMagenta
    suggestions: 
    - exit
    roamingDirectory: $APPLICATION_NAME$
    modules:
      security:
        secrets:
        - name: CommandPrompt_encryptionManager
          options:
            target: User
      storage:
        applicationDataFolder: $APPLICATION_NAME$
        backupPath: backup
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:latest
      chatGpt:
        searchUri: https://chatgpt.com/?q=$QUERY$&hints=search
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
        backgroundColor: DarkMagenta
        foregroundColor: White
      dbStorage:
        connectionString: Server=localhost;Initial Catalog=$APPLICATION_NAME$Db;User Id=$APPLICATION_NAME$_user;Password=Strong!Passw0rd;TrustServerCertificate=true;
        provider: sqlserver        
        typeMappingsRaw:
          string: "NVARCHAR(100)"
          int: "INT"
          guid: "UNIQUEIDENTIFIER"
          datetime: "DATETIME2"
          bool: "BIT"
          double: "FLOAT"
          float: "REAL"
          decimal: "DECIMAL(18, 2)"
          long: "BIGINT"
          short: "SMALLINT"
          byte: "TINYINT"
          char: "CHAR(1)"
          byte[]: "VARBINARY(MAX)"
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug