version: 1.0
configuration:
  promptKit:
    outputPath: ""
    configurationTemplate: default_CommandPromptConfiguration.yaml
    updateFilename: CommandPromptModules
    ignores:
    - bin
    - obj
    - CommandPromptConfiguration.yaml
    - CodeMap_Runtime.dgml
    - ModulesConfiguration.cs
  core:
    name: PromptKit
    version: 1.0
    prompt: pcm>
    defaultCommand: ''
    showLogo: true
    logoColor: DarkMagenta
    suggestions:
    - cd ..\..\..\..\PainKiller.CommandPrompt.CoreLib\modules
    - exit
    roamingDirectory: PromptKit
    modules:
      security:
        secrets:        
        - name: babar
          options:
            target: User
      storage:
        applicationDataFolder: $ROAMING$\PromptKit
        backupPath: backup
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:27b
      chatGpt:
        searchUri: https://chatgpt.com/?q=$QUERY$&hints=search
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
        backgroundColor: DarkMagenta
        foregroundColor: White
      dbStorage:
        connectionString: Server=192.168.0.16;Initial Catalog=PromptKit;User Id=promptKit_user;Password=Strong!Passw0rd;TrustServerCertificate=true;
        provider: sqlserver        
        typeMappingsRaw:
          string: "NVARCHAR(100)"
          int: "INT"
          guid: "UNIQUEIDENTIFIER"
          datetime: "DATETIME2"
          bool: "BIT"
          double: "FLOAT"
          float: "REAL"
          decimal: "DECIMAL(18, 2)"
          long: "BIGINT"
          short: "SMALLINT"
          byte: "TINYINT"
          char: "CHAR(1)"
          byte[]: "VARBINARY(MAX)"
      pgp:
        publicKeyFilePath: Modules\PgpModule\Bob_public.asc
        privateKeyFilePath: Modules\PgpModule\Bob_private.asc
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug 
