version: 1.0
configuration:
  name: Prompt Kit
  prompt: cp>
  defaultCommand: 'hello'
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug
  suggestions:
  - exit
