version: 1.0
configuration:
  promptKit:
    outputPath: ""
    configurationTemplate: default_CommandPromptConfiguration.yaml
    ignores:
    - bin
    - obj
    - CommandPromptConfiguration.yaml
    - CodeMap_Runtime.dgml
    - ModulesConfiguration.cs
  core:
    name: PromptKit
    version: 1.0
    prompt: pcm>
    defaultCommand: ''
    showLogo: true
    suggestions:
    - cd ..\..\..\..\PainKiller.CommandPrompt.CoreLib\modules
    - exit
    roamingDirectory: PromptKit
    modules:
      security:
        secrets:        
        - name: babar
          options:
            target: User
      storage:
        applicationDataFolder: PromptKit
        backupPath: backup
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:latest
      chatGpt:
        searchUri: https://chatgpt.com/?q=$QUERY$&hints=search
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug 
