version: 1.0
configuration:
  promptKit:
    outputPath: output
    ignores: []
  core:
    name: PromptKit
    version: 1.0
    prompt: pcm>
    defaultCommand: ''
    showLogo: true
    suggestions:
    - cd ..\..\..\..\PainKiller.CommandPrompt.CoreLib\modules
    - exit
    roamingDirectoryName: CommandPrompt
    modules:
      security:
        secrets:
        - name: CommandPrompt_encryptionManager
          options:
            target: User
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug 
