version: 1.0
configuration:
  promptKit:
    outputPath: ""
    configurationTemplate: default_CommandPromptConfiguration.yaml
    ignores:
    - bin
    - obj
    - CommandPromptConfiguration.yaml
    - CodeMap_Runtime.dgml
    - ModulesConfiguration.cs
  core:
    name: PromptKit
    version: 1.0
    prompt: pcm>
    defaultCommand: ''
    showLogo: true
    suggestions:
    - cd ..\..\..\..\PainKiller.CommandPrompt.CoreLib\modules
    - exit
    roamingDirectoryName: CommandPrompt
    modules:
      security:
        secrets:        
        - name: babar
          options:
            target: User
      storage:
        applicationDataFolder: PromptKit
        backupPath: backup
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug 
