version: 1.0
configuration:
  core:
    name: Prompt Kit
    version: "1.0"
    prompt: cp>
    defaultCommand: 'hello'
    showLogo: true
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug
  suggestions:
  - exit
  security:
    secrets:
    - name: CommandPrompt_encryptionManager
      options:
        target: User
