version: 1.0
configuration:
  custom:    
  core:
    name: $APPLICATION_NAME$
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    suggestions: []
    roamingDirectoryName: CommandPrompt
    modules:
      security:
        secrets:
        - name: CommandPrompt_encryptionManager
          options:
            target: User
      storage:
        applicationDataFolder: $APPLICATION_NAME$
        backupPath: backup
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug