version: 1.0
configuration:
  custom:    
  core:
    name: $APPLICATION_NAME$
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    suggestions: 
    - exit
    roamingDirectoryName: CommandPrompt
    modules:
      security:
        secrets:
        - name: CommandPrompt_encryptionManager
          options:
            target: User
      storage:
        applicationDataFolder: $APPLICATION_NAME$
        backupPath: backup
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:latest
      chatGpt:
        searchUri: https://chatgpt.com/?q=$QUERY$&hints=search
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug